### ISSUE TITLE
フォームのバリデーションチェック

### ISSUE THREAD

**Issue by Maple0922** [Maple0922/ksre2#29]
ずいくん頑張れ

**Comment by zui41** [comment]
Assigneesを回していただけないでしょうか？

**Comment by Maple0922** [comment]
これ？

**Comment by zui41** [comment]
👾👾👾👾👾👾💩💩💩💩💩💩

令和2年3月10日(火) 13:05 Futo Nakajima <notifications@github.com>:

**Comment by Maple0922** [comment]
????????wwwwwwww?????????wwww??????wwwww

**Comment by zui41** [comment]
🍆🍆🍆🍆🍆🍆🍆🍆🍆

**Comment by Maple0922** [comment]
チェック項目

1. 存在する日付か
2. 今日以降か
3. 時間が既存のデータと被ってないか
4. スタートタイムの方が先か( startTimeHour <= endTimeHour )
5. 練習時間は2時間以下か( startTimeHour - endTimeHour <= 2 )

**Comment by zui41** [comment]
`練習時間は2時間以下か( startTimeHour - endTimeHour <= 2 )`

は必要でしょうか？

**Comment by Maple0922** [comment]
14-18とかのガイジ 予約するやつおらんかな
わざとにしてもミスにしても

**Comment by Maple0922** [comment]
まあでも1~4は本来ありえない入力値で、5はまあ現実的でなくもないから優先度的には一番下やね

一応受け付けられない入力値は弾けるなら弾きたいし、`スタートタイムの方が先か( startTimeHour <= endTimeHour )`をちょっといじれば実装できそうだから念のためにって感じ

**Comment by Maple0922** [comment]
コメントがslackに飛ぶようにしました！

**Comment by Maple0922** [comment]
お疲れ様でした！あとで本番環境にも反映させます
