### ISSUE TITLE
予約一覧の並び替え

### ISSUE THREAD

**Issue by zui41** [Maple0922/ksre2#34]
現状の予約一覧は、startTimeHourで並び替えているので、minの方で順番が逆になることがあります。

<img width="563" alt="Screen Shot 2020-03-11 at 15 51 14" src="https://user-images.githubusercontent.com/55335284/76390332-92697480-63b0-11ea-90b2-8e1266acfcd9.png">

**Comment by Maple0922** [comment]
👍
